#
# Run:
#   docker-compose up -d
#
# Create a Postgres and Hasura container as the target data platform which Crudio will populate with test data
#

version: '3.4'

services:
  db:
    container_name: crudio_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: crudio
      POSTGRES_DB: crudio
    volumes:
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: always

  gql:
    container_name: crudio_gql
    image: hasura/graphql-engine 
    depends_on:
      - db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:crudio@db:5432
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: crudio
    ports: 
      - "6789:8080"
    restart: always
    command:
      - graphql-engine
      - serve